version: "3"
services:
  app:
    build: .
    command: python manage.py runserver 0:8000
    ports:
      - "8091:8000"
    volumes:
      - .:/code
      - /Users/patricktchankue/Downloads:/downloads
      - /Volumes:/mnt/example