# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_mytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/uploads/')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_img', to='main_app.Article')),
            ],
        ),
    ]
