# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-22 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20180119_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytable',
            options={'permissions': (('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol'))},
        ),
    ]
