# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20180122_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='article',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
